name: Release to Docker Hub

on:
  push:
    branches: [ "main" ]
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install dependencies
      run: go mod download

    - name: Build the application
      run: go build -o main .

    - name: Run tests
      run: go test ./...

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  helm:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Helm
      uses: azure/setup-helm@v1

    # - name: Deploy Helm Chart
    #   env:
    #     KUBECONFIG: ${{ secrets.KUBECONFIG }}
    #   run: |
    #     helm upgrade --install go-microservice ./helm/go-microservice --set image.repository=yourusername/go-microservice --set image.tag=latest
# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

#       - name: Install Go
#         uses: actions/setup-go@v3
#         with:
#           go-version: 1.18

#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Fetch required Go modules
#         run:  go mod download

#       - name: Build
#         run:  go build -v ./...

#       - name: Test
#         run: go test -v ./...

#       # - name: Build and push Docker image
#       #   id:   docker_build
#       #   uses: docker/build-push-action@v3
#       #   with:
#       #     push: true
#       #     tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

#       # - name: Image digest
#       #   run: echo ${{ steps.docker_build.outputs.digest }}
#     docker:
  